-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Custom"
(
    id serial NOT NULL,
    group_id integer NOT NULL,
    movie_id integer NOT NULL,
    showtime_id integer NOT NULL,
    CONSTRAINT "Custom_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Favorites"
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    movie_id integer NOT NULL,
    CONSTRAINT "Favorites_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."GroupMembers"
(
    group_id integer NOT NULL,
    user_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Groups"
(
    id serial NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    creator_id integer NOT NULL,
    CONSTRAINT "Groups_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Movies"
(
    id integer NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    release_date date,
    genre character varying(150) COLLATE pg_catalog."default",
    CONSTRAINT "Movies_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Review"
(
    id serial NOT NULL,
    movie_id integer NOT NULL,
    user_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    stars integer NOT NULL,
    "timestamp" timestamp(6) without time zone NOT NULL,
    comment text COLLATE pg_catalog."default",
    CONSTRAINT "Review_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Showtimes"
(
    id integer NOT NULL,
    movie_id integer,
    theater character varying(150) COLLATE pg_catalog."default",
    show_date date,
    show_time time without time zone,
    CONSTRAINT "Showtimes_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Users"
(
    id serial NOT NULL,
    email character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public."Custom"
    ADD CONSTRAINT "Custom_group_id_fkey" FOREIGN KEY (group_id)
    REFERENCES public."Groups" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Custom"
    ADD CONSTRAINT "Custom_movie_id_fkey" FOREIGN KEY (movie_id)
    REFERENCES public."Movies" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Custom"
    ADD CONSTRAINT "Custom_showtime_id_fkey" FOREIGN KEY (showtime_id)
    REFERENCES public."Showtimes" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Favorites"
    ADD CONSTRAINT "Favorites_movie_id_fkey" FOREIGN KEY (movie_id)
    REFERENCES public."Movies" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Favorites"
    ADD CONSTRAINT "Favorites_user_id_fkey" FOREIGN KEY (user_id)
    REFERENCES public."Users" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."GroupMembers"
    ADD CONSTRAINT "GroupMembers_group_id_fkey" FOREIGN KEY (group_id)
    REFERENCES public."Groups" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."GroupMembers"
    ADD CONSTRAINT "GroupMembers_user_id_fkey" FOREIGN KEY (user_id)
    REFERENCES public."Users" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Groups"
    ADD CONSTRAINT "Groups_creator_id_fkey" FOREIGN KEY (creator_id)
    REFERENCES public."Users" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Review"
    ADD CONSTRAINT "Review_movie_id_fkey" FOREIGN KEY (movie_id)
    REFERENCES public."Movies" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Review"
    ADD CONSTRAINT "Review_user_email_fkey" FOREIGN KEY (user_email)
    REFERENCES public."Users" (email) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Showtimes"
    ADD CONSTRAINT movie_id FOREIGN KEY (movie_id)
    REFERENCES public."Movies" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;